/**
 * The HTML report.
 *
 * One self-contained file: no external CSS, no fonts, no scripts. It gets attached to a
 * ticket, emailed, or opened from a download folder six weeks later, and it has to work in
 * all of those without a server.
 *
 * The audience is mixed — a PM may write the ticket, an engineer fixes it — so each finding
 * leads with plain English and carries the exact request and response underneath. Nobody
 * should have to take the report's word for anything.
 */
import { sortFindings, summarise } from '../findings.js';

const TONE = {
  blocker: { label: 'Blocker', colour: '#b91c1c', background: '#fef2f2' },
  major: { label: 'Major', colour: '#c2410c', background: '#fff7ed' },
  minor: { label: 'Minor', colour: '#a16207', background: '#fefce8' },
  info: { label: 'Info', colour: '#1d4ed8', background: '#eff6ff' },
};

export function renderHtml({ findings, target, startedAt, finishedAt, suites }) {
  const sorted = sortFindings(findings);
  const summary = summarise(findings);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>API verification — ${escape(target)}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 2rem 1.5rem; background: #f8fafc; color: #0f172a;
    font: 15px/1.6 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
  }
  main { max-width: 60rem; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin: 0 0 .25rem; }
  .meta { color: #64748b; font-size: .875rem; margin-bottom: 1.5rem; }
  .verdict {
    padding: 1rem 1.25rem; border-radius: .5rem; margin-bottom: 1.5rem;
    border: 1px solid ${summary.passed ? '#bbf7d0' : '#fecaca'};
    background: ${summary.passed ? '#f0fdf4' : '#fef2f2'};
  }
  .verdict strong { font-size: 1.05rem; }
  .counts { display: flex; flex-wrap: wrap; gap: .5rem; margin-top: .75rem; }
  .count {
    padding: .2rem .6rem; border-radius: 999px; font-size: .8rem; font-weight: 600;
    border: 1px solid currentColor;
  }
  article {
    background: #fff; border: 1px solid #e2e8f0; border-radius: .5rem;
    margin-bottom: 1rem; overflow: hidden;
  }
  .head { padding: .9rem 1.1rem; border-bottom: 1px solid #f1f5f9; }
  .badge {
    display: inline-block; padding: .1rem .5rem; border-radius: .25rem;
    font-size: .75rem; font-weight: 700; letter-spacing: .02em; text-transform: uppercase;
  }
  .title { font-weight: 600; margin: .4rem 0 0; }
  .body { padding: .9rem 1.1rem; }
  .body p { margin: 0 0 .6rem; }
  .why { color: #475569; }
  .expected {
    display: flex; flex-wrap: wrap; gap: 1.5rem; margin: .75rem 0 0;
    font-size: .875rem; color: #334155;
  }
  .expected code { background: #f1f5f9; padding: .1rem .35rem; border-radius: .25rem; }
  details { margin-top: .9rem; border-top: 1px solid #f1f5f9; padding-top: .75rem; }
  summary { cursor: pointer; color: #475569; font-size: .875rem; }
  pre {
    background: #0f172a; color: #e2e8f0; padding: .75rem; border-radius: .375rem;
    overflow-x: auto; font-size: .8125rem; line-height: 1.5; margin: .5rem 0 0;
  }
  .label { font-size: .75rem; text-transform: uppercase; letter-spacing: .04em; color: #64748b; margin-top: .75rem; }
  footer { color: #64748b; font-size: .8125rem; margin-top: 2rem; }
  @media print { body { background: #fff; } article { break-inside: avoid; } }
</style>
</head>
<body>
<main>
  <h1>API verification report</h1>
  <p class="meta">
    ${escape(target)}<br>
    ${escape(new Date(startedAt).toLocaleString())} ·
    ${Math.round((finishedAt - startedAt) / 100) / 10}s ·
    suites: ${suites.map(escape).join(', ')}
  </p>

  <div class="verdict">
    <strong>${summary.passed ? 'No blocking problems found' : `${summary.total} problem${summary.total === 1 ? '' : 's'} found`}</strong>
    <div class="counts">
      ${['blocker', 'major', 'minor', 'info']
        .filter((s) => summary[s] > 0)
        .map(
          (s) =>
            `<span class="count" style="color:${TONE[s].colour}">${summary[s]} ${TONE[s].label.toLowerCase()}</span>`,
        )
        .join('')}
    </div>
  </div>

  ${sorted.map(renderFinding).join('\n')}

  ${sorted.length === 0 ? '<p>Every check passed.</p>' : ''}

  <footer>
    Generated by ReqLab REST. Every finding above includes the exact request and response that
    produced it — expand “Evidence” to see them. Secret values are masked.
  </footer>
</main>
</body>
</html>`;
}

function renderFinding(f) {
  const tone = TONE[f.severity];

  return `<article>
  <div class="head" style="background:${tone.background}">
    <span class="badge" style="color:${tone.colour};border:1px solid ${tone.colour}">${tone.label}</span>
    ${f.endpoint ? `<span style="color:#475569;font-size:.8125rem"> ${escape(f.endpoint)}</span>` : ''}
    <p class="title">${escape(f.title)}</p>
  </div>
  <div class="body">
    <p>${escape(f.whatHappened)}</p>
    <p class="why">${escape(f.whyItMatters)}</p>
    ${
      f.expected !== null || f.actual !== null
        ? `<div class="expected">
             <span>Expected: <code>${escape(String(f.expected ?? '—'))}</code></span>
             <span>Actual: <code>${escape(String(f.actual ?? '—'))}</code></span>
             ${f.specRef ? `<span>Spec: <code>${escape(f.specRef)}</code></span>` : ''}
           </div>`
        : ''
    }
    ${f.evidence ? renderEvidence(f.evidence) : ''}
  </div>
</article>`;
}

function renderEvidence(evidence) {
  const { request, response, timingMs } = evidence;

  return `<details>
  <summary>Evidence — the request and response that produced this</summary>
  <div class="label">Request</div>
  <pre>${escape(
    [
      `${request.method} ${request.url}`,
      ...Object.entries(request.headers ?? {}).map(([k, v]) => `${k}: ${v}`),
      request.body ? `\n${request.body}` : '',
    ]
      .filter(Boolean)
      .join('\n'),
  )}</pre>
  <div class="label">Response${timingMs !== null ? ` — ${timingMs} ms` : ''}</div>
  <pre>${escape(
    [
      `HTTP ${response.status} ${response.statusText ?? ''}`.trim(),
      ...Object.entries(response.headers ?? {}).map(([k, v]) => `${k}: ${v}`),
      response.body ? `\n${response.body}` : '',
    ]
      .filter(Boolean)
      .join('\n'),
  )}</pre>
</details>`;
}

/**
 * Escape for HTML.
 *
 * The report embeds an API's own responses, which are not ours and may contain anything. A
 * self-contained file that executes a script it found in a response body would be a way of
 * attacking the person reading the report.
 */
function escape(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
